version: '3.8'

services:
  postgres:
    image: postgres
    container_name: bloggercontainer
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:5432"
